@host = http://localhost:5277
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName": "Aurelio",
    "email": "teste@gmail.com",
    "password": "A123&!"
}