version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: marco@localhost.com
      PGADMIN_DEFAULT_PASSWORD: marco@localhost.com
    ports:
      - "5050:80"
    depends_on:
      - postgres

  seq:
    image: datalust/seq:latest
    container_name: seq-container
    environment:
      ACCEPT_EULA: Y
    ports:
      - "80:80"
      - "5341:5341"
    restart: unless-stopped
    volumes:
      - seq-data:/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
  seq-data:
