@host = http://localhost:5277
GET {{host}}/mainfeed

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNTZlN2M4OC00YzdhLTQxZDktYjdhMS0zZmUzZDc0MDJiYTYiLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6IkF1cmVsaW8iLCJqdGkiOiJhZTk1OTIzZS0xMjdlLTQwYWMtYmVmYi0xMDBlYjliM2FmMmMiLCJleHAiOjE3MDQ5MzAzMjIsImlzcyI6IlJlZGRpdENsb25lIiwiYXVkIjoiUmVkZGl0Q2xvbmUifQ.nclNom9D8sYETn2ao2XlS0lgFBOpkiK2SyM1hoCWWtY