@host = http://localhost:5277
@userId =
POST {{host}}/community/{{userId}}
Content-Type: application/json

{
    "name": "C#",
    "description": "hello i am a description",
    "membersCount": 0,
    "topic": "Programming"
}